### ISSUE TITLE
代币的智能合约已经发布，那应该怎么写批量转账？？

### ISSUE THREAD

**Issue by lancesf** [xianfeng92/Love-Ethereum#2]
代币的合约已经发布了，智能合约应该不能修改吧？？
是不是应该再写一个批量转账的智能合约，去请求代币那个智能合约？？？怎么弄？？？？

**Comment by xianfeng92** [comment]
如果只是自己在网弄着测试玩～可以在部署一个合约去调用代币合约的转账功能。
要是工程用，个人建议还是重新部署一个。

**Comment by atlaschiew** [comment]
> 代币的合约已经发布了，智能合约应该不能修改吧？？
> 是不是应该再写一个批量转账的智能合约，去请求代币那个智能合约？？？怎么弄？？？？

可以看看这里 https://www.btcschools.net/eth_smartcontract/eth_sc_multi_send_erc20.php

我是btcschools这个项目的作者，希望对你有帮助
